#!/usr/bin/env python

from __future__ import print_function

import sys

from subprocess import Popen, PIPE
from multiprocessing import Event, Pool, Process, Queue
import time

try:
    from Queue import Empty as Queue_Empty
except ImportError:
    from queue import Empty as Queue_Empty


def run_subprocess(cmd):
    sp = Popen(cmd, stdout=PIPE, stderr=PIPE,
               shell=True, universal_newlines=True)
    comm = sp.communicate()
    exit_code = sp.returncode
    if exit_code != 0:
        print("There was an error running the subprocess.\n"
              "cmd: %s\n"
              "exit code: %d\n"
              "stdout: %s\n"
              "stderr: %s" % (cmd, exit_code, comm[0], comm[1]))
    return comm


def get_commits(commitlist, lastcommit):
    cmd = "git log --format=%%H %s | sed '/%s/q'" % (commitlist, lastcommit)
    comm = run_subprocess(cmd)
    return comm[0].strip("\n").split("\n")


def get_total_changes(commit):
    cmd = "git diff %s --shortstat" % commit
    comm = run_subprocess(cmd)
    total = 0
    for i in comm[0].split(',')[1:]:
        a = int(i.split()[0])
        total = total + a
    return total


def worker(commit):
    tc = get_total_changes(commit)
    worker.q.put((commit, tc))


def worker_init(q):
    worker.q = q


def background(q, e, s):
    best = 9999999999999
    commit = ""
    while True:
        try:
            tn, tc = q.get(False)
        except Queue_Empty:
            if e.is_set():
                break
        else:
            if not s:
                print("%s has %d lines changed" % (tn, tc))
            if best > tc:
                best = tc
                commit = tn
                if not s:
                    print("%s is the new best match with %d lines changed" % (tn, tc))
    print("Best commit")
    print("commit: %s" % commit)
    print("Lines changed: %d" % best)


def main():
    import argparse  # Only needed for main()
    parser = argparse.ArgumentParser()
    parser.add_argument("-j", action="store", dest="jobs", default=1, type=int,
                        metavar="N", help="number of jobs to run at once")
    parser.add_argument("-s", action="store_true", dest="silent", default=False,
                        help="reduce the verbosity of the output")
    parser.add_argument("commitlist", metavar="<xxx^..yyy>",
                       help="commits list as xxxxx^..yyyyy to iterate into")
    args = parser.parse_args()

    a = args.commitlist.split("^")[0]
    commits = get_commits(args.commitlist, a)
    if not commits:
        print("No commits to check. bailing.")
        sys.exit(1)
    if not args.silent:
        print("number of commits to check: %d" % len(commits))

    queue = Queue()
    event = Event()

    b = Process(target=background, args=(queue, event, args.silent))
    b.start()

    pool = Pool(args.jobs, worker_init, [queue])
    pool.map(worker, commits)

    pool.close()
    pool.join()
    event.set()
    b.join()


if __name__ == '__main__':
    main() 
